### ISSUE TITLE
Display Street View images

### ISSUE THREAD

**Issue by HarryPotia** [WeAreSnook/connected-camden#204]
> As a user, I want to be able to view Google Street View images on the output route directions, so that I visualise the directions and follow them more easily during travel.

This is described by other tickets.

## Stories

- [x] Create a valid streetview url #190
- [x] Create a streetview component #189
- [x] Fetch an image for each step in the journey #150
