### ISSUE TITLE
Setup to deploy our code on Government PaaS

### ISSUE THREAD

**Issue by mathewtrivett** [WeAreSnook/connected-camden#78]
> As Camden Council
> I want the code to be hosted on Government approved infrastructure
> So that we can fulfil our responsibilities as a data controller

## Description

[Government PaaS](https://www.cloud.service.gov.uk/) is like Heroku for public sector projects. It allows us to host our software  in the cloud on government approved infrastructure. As a public sector organisation, Camden Council want to us to host on Gov PaaS.

This may involve onboarding Camden's technical team to using Gov PaaS at a later date. I feel like this might be best written up as a separate ticket when we know more.

## Acceptance criteria

- [ ] We can deploy our code to their staging environment
- [ ] We can deploy to their production environment
- [ ] We document our decision to use Government PaaS as a technical decision
- [ ] We document how to deploy the project to our staging and production environments
- [ ] Add documentation on [how to deploy to Government PaaS in the developer manual](https://github.com/wearesnook/developer-manual) 
- [ ] Technical teams from Camden are aware and approve of us hosting the service using Government PaaS
- [ ] It should have a `manifest.yml` configuration file

## Notes and links

Here is a [how to get started guide from GDS](https://www.cloud.service.gov.uk/get-started/)

## Blockers

Currently blocked because:

- [x] We need a .gov.uk email (See #79 )
- [ ] We need to register a domain name (See #81)
- [ ] We need documentation (See #87 )

**Comment by mathewtrivett** [comment]
Currently blocked because we need a .gov.uk email (See #79 )

**Comment by mathewtrivett** [comment]
I’m going to keep this open but move it to the bottom of the backlog in case we want in future to deploy to gov paas

**Comment by mathewtrivett** [comment]
Closing this issue for now as not currently planning to deploy to GOV PaaS see #82
